ktor:
  deployment:
    port: 8080
    watch: [ classes ]
  application:
    modules: [ com.example.ApplicationKt.module ]

jwt:
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/api"
  realm: "Ktor Server"
  secret: "supersecretkey"